---
title: "The R Inferno"
output: 
  html_document:
    code_folding: hide
---

Welcome to this repository. This is a exercise of the [Workshop: "Developing skills in R"](https://deepskillsr.github.io/). Given at [Stockholm University](https://www.su.se/deep/english/about-us/events/workshop-developing-skills-in-r-1.402004). In this exercise we re-edit [The R Inferno book](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf) written by [Patrick Burns](https://www.burns-stat.com/) in RMarkdown.  
If you want to contribute to this new editions. follow these instructions:

- First of all, you need to have access to this repository (if you don't have it, ask to the teachers).

- Clone this repository, and create a new branch (name it your_name_br). 
```{bash, eval=F}
git clone https://github.com/TheRInferno/TheRInferno.github.io
git branch your_name_br
git checkout your_name_br
```

- Chose a chapter of the book and re-write it in RMarkdown (use also the xaringan if you want to do a presentation). The name have to be be Ch_X_your_name (Use the chunk for the R code, add also other images ...).

- Knit your RMarkdown file.

- Add the files created to the staging area. 
```{bash, eval=F}
git add file1
git add file2
```

- Commit the changes and push it.
```{bash, eval=F}
git commit -m 'my page'
git push origin your_name_br
```

- If you are happy of your work, go back to the master branch.
```{bash, eval=F}
git checkout master

```

- pull the last version of the repository.
```{bash, eval=F}
git pull
```

- merge your branch with the master.
```{bash, eval=F}
git merge your_name_br
```

- Modify the book.Rmd file, add the line with the link to your page.
```{r, eval=F}
[Ch_X by your_name](Ch_X_your_name.html)
```

- Knit the book.Rmd file.

- Add the book.Rmd, book.html
```{bash, eval=F}
git book*
```


- commit your change and push you local repository
```{bash, eval=F}
git commit -m 'my links'
git push origin master
```


Now, You can see your contribution [here](https://TheRInferno.github.io/book.html), refesh and at the top of the page the link to your chapter should appear.

